- .github/workflows/lint-test.yml
- lua/fugit2/utils.lua
- tests/fugit2/fugit2_utils_spec.lua
- tests/fugit2/view/commit_log_view_spec.lua
Fix failed tests:
- Fix failed tests on intel machine.
- Use mac arm as test ci in addition to amd64 linux.
> Fix test on intel machine

- README.md
> chore: add graph view screenshot

- lua/fugit2/init.lua
- lua/fugit2/view/ui.lua
Current logic will open git folder at vim cwd. From now, current working directory will be calculated based on buffer file directory.
> feat: change git cwd logic

- README.md
- lua/fugit2/view/components/commit_log_view.lua
- lua/fugit2/view/git_graph.lua
- lua/fugit2/view/git_status.lua
> feat: allow copy commit id

- lua/fugit2/view/git_status.lua
Fix file opening when cwd != git path dir
> fix: fix open file

- README.md
> chore: add gpgme to readme

- lua/fugit2/view/components/file_tree_view.lua
- lua/fugit2/view/git_status.lua
Fix buffer modified status missing
> feat: fix buffer modified status

- lua/fugit2/git2.lua
- lua/fugit2/libgit2.lua
> feat: rework GitIndexEntry

- README.md
- lua/fugit2/init.lua
- lua/fugit2/view/components/file_tree_view.lua
- lua/fugit2/view/git_status.lua
- lua/fugit2/view/ui.lua
Allow user config layout size. Check README for more details
> feat: allow user config layout size

- README.md
> Add rocks.nvim to README

- lua/fugit2/notifier.lua
- lua/fugit2/view/components/base_tree_view.lua
- lua/fugit2/view/components/file_tree_view.lua
- lua/fugit2/view/components/source_tree_view.lua
- lua/fugit2/view/git_base_view.lua
- lua/fugit2/view/git_diff.lua
- lua/fugit2/view/git_rebase.lua
- lua/fugit2/view/git_status.lua
- tests/minimal_init.lua
> Add stage unstage in diffview

- lua/fugit2/diff.lua
- lua/fugit2/view/components/patch_view.lua
- lua/fugit2/view/git_status.lua
- tests/fugit2/diff_spec.lua
- tests/minimal_init.lua
Now, press Enter in patch view will help you jump to file with corresponding line.
> feat: add jumping to file from hunk

- README.md
- lua/fugit2/init.lua
- lua/fugit2/view/components/source_tree_view.lua
- lua/fugit2/view/git_diff.lua
- lua/fugit2/view/git_status.lua
- plugin/fugit2.lua
Replace diffview.nvim with built-in diffview
> Replace diffview.nvim with built-in diffview

- lua/fugit2/core/git_gpg.lua
- lua/fugit2/git2.lua
- lua/fugit2/libgit2.lua
- lua/fugit2/notifier.lua
- lua/fugit2/view/git_status.lua
After this pull request, we can extend, amend commit with gpg signing config
> feat: amend commit with gpg

- lua/fugit2/view/git_status.lua
Pass git_path to cwd args of PlenaryJob
> Fix git push/pull command cwd

- lua/fugit2/core/git_gpg.lua
- lua/fugit2/view/git_status.lua
Add ssh signing via `ssh-keygen -Y sign`
> Add ssh signing reword

- .github/workflows/lint-test.yml
- .styluaignore
- README.md
- lua/fugit2/core/blame.lua
- lua/fugit2/core/fzf.lua
- lua/fugit2/core/matrix.lua
- lua/fugit2/core/pendulum.lua
- lua/fugit2/git2.lua
- lua/fugit2/init.lua
- lua/fugit2/libgit2.lua
- lua/fugit2/utils.lua
- lua/fugit2/view/colors.lua
- lua/fugit2/view/components/patch_view.lua
- lua/fugit2/view/git_blame.lua
- lua/fugit2/view/git_blame_line.lua
- lua/fugit2/view/git_diff.lua
- lua/fugit2/view/git_graph.lua
- lua/fugit2/view/git_pick.lua
- lua/fugit2/view/git_status.lua
- lua/fugit2/view/ui.lua
- plugin/fugit2.lua
- tests/fugit2/core/blame_spec.lua
- tests/fugit2/core/fzf_spec.lua
- tests/fugit2/core/pendulum_spec.lua
- tests/fugit2/git2_spec.lua
- tests/resources/blame_a.txt
- tests/resources/blame_b.txt
> Add git blame

- .github/workflows/lint-test.yml
- .github/workflows/luarocks.yml
- .github/workflows/rockspec.template
- Makefile
- nlua.busted
- spec/fugit2/diff_spec.lua
- spec/fugit2/git2_spec.lua
Fix luarocks upload error with nlua
> Fix luarocks upload

- lua/fugit2/git2.lua
- lua/fugit2/libgit2.lua
- lua/fugit2/utils.lua
- lua/fugit2/view/git_status.lua
Make main fugit2 window truly async.
- Add status_async to libgit2.
- Change render functions of GitStatusView.
> feat: make git status async

- lua/fugit2/view/components/patch_view.lua
- lua/fugit2/view/git_status.lua
Show line number in patch view
> feat: show line number in patch view

- lua/fugit2/view/git_status.lua
Close https://github.com/SuperBo/fugit2.nvim/issues/71
> fix push upstream with slash in name

- lua/fugit2/core/pendulum.lua
- lua/fugit2/git2.lua
- lua/fugit2/view/colors.lua
- lua/fugit2/view/components/commit_log_view.lua
- lua/fugit2/view/git_graph.lua
- lua/fugit2/view/git_status.lua
https://github.com/SuperBo/fugit2.nvim/issues/66
> feat: add lazy loading for git graph

- lua/fugit2/view/components/file_tree_view.lua
add number of sub files to collapsed directory.
> feat: add number of sub files

- lua/fugit2/view/components/file_tree_view.lua
- lua/fugit2/view/git_base_view.lua
- lua/fugit2/view/git_graph.lua
- lua/fugit2/view/git_status.lua
- lua/fugit2/view/ui.lua
- Fix https://github.com/SuperBo/fugit2.nvim/issues/18.
- Implement https://github.com/SuperBo/fugit2.nvim/issues/28.
> Fix git graph issues

- Makefile
- lua/fugit2/utils.lua
- lua/fugit2/view/components/file_tree_view.lua
- spec/fugit2/utils_spec.lua
Should solve https://github.com/SuperBo/fugit2.nvim/issues/91
> feat: compress path in file tree

- lua/fugit2/view/git_status.lua
Fix discard directory in normal mode
> Fix discard directory in normal mode

- lua/fugit2/utils.lua
- lua/fugit2/view/components/file_tree_view.lua
- spec/fugit2/utils_spec.lua
Directory is not properly sorted. This is to fix that issues.
> feat: sort directory in dir tree

- lua/fugit2/core/gpgme.lua
- lua/fugit2/git2.lua
- lua/fugit2/init.lua
- lua/fugit2/libgit2.lua
- spec/fugit2/diff_spec.lua
- spec/fugit2/git2_spec.lua
Separate init and setup process. Make use of lazy_C attribute to make C library loading process lazy.
> feat: separate init and setup

- lua/fugit2/view/git_status.lua
Show git log while showing command instead of file popup
> Show git log while showing command

- README.md
- lua/fugit2/config.lua
- lua/fugit2/view/git_status.lua
Add config option to show patch on open
> Add config option to show patch on open

- lua/fugit2/view/git_status.lua
Fix show patch display mentioned in this https://github.com/SuperBo/fugit2.nvim/issues/102#issuecomment-2483773377
> Fx show patch display

- .pre-commit-config.yaml
- lua/fugit2/core/git_hooks.lua
- lua/fugit2/utils.lua
- lua/fugit2/view/git_status.lua
> feat: add pre-commit support

- .github/workflows/lint-test.yml
- .pre-commit-config.yaml
- README.md
Add build = false to tell lazy.nvim to not build this plugin
> chore: change lazygit default config

- README.md
- lua/fugit2/config.lua
- lua/fugit2/view/git_status.lua
> feat: add command timeout config

- README.md
- lua/fugit2/view/components/file_tree_view.lua
- lua/fugit2/view/git_status.lua
Add loading text to git status, useful on big repo.
Also add link to https://github.com/libgit2/libgit2/issues/4230
> feat: add loading text to git status

- lua/fugit2/view/git_status.lua
Add option to push to gerrit review.
> feat: add git push review

- .github/workflows/lint-test.yml
- .stylua.toml
Update stylua to version 2.1.0.
> chore: update stylua in ci
